valid_json_format_calc = {
    "age": int,
    "parity": int,
    "gdm": bool,
    "congenital": bool,
    "stillbirth": bool,
    "miscarriage": bool,
    "preterm": bool,
    "macrosomia": bool,
    "height": int,
    "weight": int,
    "white": bool,
    "family_diabetes": bool,
    "polycystic": bool,
    "blood_pressure_family": bool,
    "blood_pressure_not_family": bool,
    "diet_not_varied": bool,
    "diet_sugar": bool,
    "diet_sweets": bool,
    "diet_processed_meat": bool,
    "diet_whole_grain": bool,
    "diet_diary": bool,
    "diet_vitamin_d": bool,
    "activity_walking_minute": bool,
    "activity_vigorous": bool,
    "activity_stairs": bool
}