module.exports = {
  factors: [
    {
      factor: "age",
      question: "Please enter your current age",
      answertype: "int",
      skippable: false,
      maxdigits: 2,
    },
    {
      factor: "parity",
      question:
        "Please enter the number of times you previously have been pregnant, including births and stillbirths",
      answertype: "int",
      skippable: false,
      maxdigits: 1,
      requirement: ">;0",
      subfactors: [
        {
          factor: "gdm",
          question:
            "Do you currently have, or have previously had Gestational diabetes?",
          answertype: "boolean",
          skippable: false,
        },
        {
          factor: "congenital",
          question: "Do you have any children with congenital disorder?",
          answertype: "boolean",
          skippable: false,
        },
        {
          factor: "stillbirth",
          question: "Have you previously had any stillbirths?",
          answertype: "boolean",
          skippable: false,
        },
        {
          factor: "miscarriage",
          question: "Have you had any miscarriages?",
          answertype: "boolean",
          skippable: false,
        },
        {
          factor: "preterm",
          question: "Have you previously had preterm birth?",
          answertype: "boolean",
          skippable: false,
        },
        {
          factor: "macrosomia",
          question: "Macrosomia?",
          answertype: "boolean",
          skippable: true,
        },
      ],
    },
    {
      factor: "height",
      question: "Please enter your height",
      answertype: "int",
      skippable: false,
      maxdigits: 3,
    },
    {
      factor: "weight",
      question: "Please enter your weight",
      answertype: "int",
      skippable: false,
      maxdigits: 3,
    },
    {
      factor: "family_diabetes",
      question: "Do your family have a history of diabetes?",
      answertype: "boolean",
      skippable: true,
    },
    {
      factor: "polycystic",
      question: "Do you have polycystic ovarian syndrome?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "blood_pressure_family",
      question: "Does your family have a history of high blood pressure?",
      answertype: "boolean",
      skippable: true,
    },
    {
      factor: "blood_pressure_not_family",
      question: "Do you have a high blood pressure?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "diet_not_varied",
      question: "Do you have a varied diet?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "diet_sugar",
      question: "Do you have a high sugar intake?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "diet_sweets",
      question: "Do you eat a lot of sweets?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "diet_processed_meat",
      question: "Do you eat a lot of processed meat?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "diet_whole_grain",
      question: "Do you eat a lot of whole grain?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "diet_diary",
      question: "Do you consume a lot of diary products?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "diet_vitamin_d",
      question: "Do you have normal vitamin D levels?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "activity_walking_minute",
      question: "Do you excercise for at least 30min a day?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "activity_vigorous",
      question: "Do you have vigourous exercise?",
      answertype: "boolean",
      skippable: false,
    },
    {
      factor: "activity_stairs",
      question: "Do you exercise by walking up stairs?",
      answertype: "boolean",
      skippable: false,
    },
  ],
};
