module.exports = {
    refrences:[
        {
          ref:"1"
        },
        {
            ref:"2",
            subfactors: [
                {
                    ref:"3"
                },
                {
                    ref:"4"
                },
                {
                    ref:"5"
                },
                {
                    ref:"6"
                },
                {
                    ref:"7"
                },
                {
                    ref:"8"
                },
            ]
        },
        {
            ref:"9"
        },
        {
            ref:"10"
        },
        {
            ref:"11"
        },
        {
            ref:"12"
        },
        {
            ref:"13"
        },
        {
            ref:"13"
        },
        {
            ref:"14"
        },
        {
            ref:"15"
        },
        {
            ref:"16"
        },
        {
            ref:"17"
        },
        {
            ref:"18"
        },
        {
            ref:"19"
        },
        {
            ref:"20"
        },
        {
            ref:"21"
        },
        {
            ref:"22"
        },
        {
            ref:"23"
        },
    ],
};
